server:
    port: 80
spring:
    application:
        name: appgateway
    zipkin:
        base-url: http://54.83.140.124:9411
    cloud:
        gateway:
            default-filters:
                - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            globalcors:
                corsConfigurations:
                    '[/**]':
                        allowedOrigins: "*"
                        allowedMethods: "*"
                        allowedHeaders: "*"
            routes:
                -   id: appsecurity
                    uri: http://app-service-security:80
                    predicates:
                    -   Path=/security/**
                    filters:
                    -   StripPrefix=1
                -   id: appaccount
                    uri: http://app-service-account:80
                    predicates:
                    -   Path=/account/**
                    filters:
                    -   StripPrefix=1
                    -   JwtAuthenticationFilter
                -   id: appdeposit
                    uri: http://app-service-deposit:80
                    predicates:
                    -   Path=/deposit/**
                    filters:
                    -   StripPrefix=1
                    -   JwtAuthenticationFilter
                -   id: appwithdrawal
                    uri: http://app-service-withdrawal:80
                    predicates:
                    -   Path=/withdrawal/**
                    filters:
                    -   StripPrefix=1
                    -   JwtAuthenticationFilter
                -   id: appmovements
                    uri: http://app-service-movement:80
                    predicates:
                    -   Path=/movement/**
                    filters:
                    -   StripPrefix=1

#Metrics
management:
    endpoints:
        web:
            exposure:
                include:
                    -   "*"
