server:
    port: 80
spring:
    application:
        name: appgateway
    zipkin:
        base-url: http://ec2-54-235-57-154.compute-1.amazonaws.com:9411
    cloud:
        gateway:
            default-filters:
                - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            globalcors:
                corsConfigurations:
                    '[/**]':
                        allowedOrigins: "*"
                        allowedMethods: "*"
                        allowedHeaders: "*"
            routes:
                -   id: appsecurity
                    uri: http://ec2-54-235-57-154.compute-1.amazonaws.com:9001
                    predicates:
                    -   Path=/security/**
                    filters:
                    -   StripPrefix=1
                -   id: appaccount
                    uri: http://ec2-54-235-57-154.compute-1.amazonaws.com:9002
                    predicates:
                    -   Path=/account/**
                    filters:
                    -   StripPrefix=1
                    -   JwtAuthenticationFilter
                -   id: appdeposit
                    uri: http://ec2-54-235-57-154.compute-1.amazonaws.com:9003
                    predicates:
                    -   Path=/deposit/**
                    filters:
                    -   StripPrefix=1
                    -   JwtAuthenticationFilter
                -   id: appwithdrawal
                    uri: http://ec2-54-235-57-154.compute-1.amazonaws.com:9004
                    predicates:
                    -   Path=/withdrawal/**
                    filters:
                    -   StripPrefix=1
                    -   JwtAuthenticationFilter
                -   id: appmovements
                    uri: http://ec2-54-235-57-154.compute-1.amazonaws.com:9005
                    predicates:
                    -   Path=/movement/**
                    filters:
                    -   StripPrefix=1

#Metrics
management:
    endpoints:
        web:
            exposure:
                include:
                    -   "*"
